// <auto-generated />
using System;
using Led.Database.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Led.Database.Ef.Migrations.Migrations
{
    [DbContext(typeof(LedDbContext))]
    [Migration("20240722055846_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Led.Database.Ef.EntityModel.LED", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.HasKey("Id");

                    b.ToTable("Led", "led");
                });

            modelBuilder.Entity("Led.Database.Ef.EntityModel.LedStrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("LedCount")
                        .HasColumnType("bigint");

                    b.Property<int>("LedStripTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LedStripTypeId");

                    b.ToTable("LedStrip", "led");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateUtc = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            LedCount = 0L,
                            LedStripTypeId = 1,
                            Name = ""
                        });
                });

            modelBuilder.Entity("Led.Database.Ef.EntityModel.LedStripTypeList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("LedStripTypeList", "led");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Individually addressable.",
                            Name = "WS2812B"
                        });
                });

            modelBuilder.Entity("Led.Database.Ef.EntityModel.LedStrip", b =>
                {
                    b.HasOne("Led.Database.Ef.EntityModel.LedStripTypeList", "LedStripType")
                        .WithMany()
                        .HasForeignKey("LedStripTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LedStripType");
                });
#pragma warning restore 612, 618
        }
    }
}
